on: 
  push:
    tags:
      - vTest2
name: Tag Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Debug 
      uses: actions/checkout@master
      with:
       entrypoint: ./entrypoint.sh
