on: 
  push:
    tags:
      include:
      - *
name: Tag Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Debug
      run: |
        ./entrypoint.sh 
