on: 
  push:
    tags:
      - '*'
name: Build and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Debug 
      with:
       entrypoint: ./entrypoint.sh
